apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: authzadaptor-instance
  namespace: istio-system
spec:
  template: authzadaptor
  params:
    key: request.headers["x-amzn-oidc-data"] | "unknown"