apiVersion: v1
kind: Service
metadata:
  name: authzadaptor
  namespace: istio-system
spec:
  ports:
  - port: 9070
    protocol: TCP
    targetPort: 9070
  selector:
    run: authzadaptor
  type: ClusterIP